blog: improve vercel preview article
argos-ci/argos-ci.com pull request #128
Opened 2024-02-02 20:31 UTC by jsfez

2024-02-02 22:38 UTC, gregberge requested changes
- Texts are complicated and smell AI, it has not any writer style, makes it boring to read.
- It's very hard to follow the subject because you setup the CI twice, it does not make sense.
- Writing in the first person singular makes the style heavy. Also you are writing on Argos, so we show the way. It's obvious that we are not setting this up for us. It makes it weird.
- You can refer other articles to deep dive yes, but not to avoid explaining things in this article.
- Trademarks are very important. It really is a huge lack of seriousness to forget a capital letter.
- The main image is very cheap and displays "localhost:3000". I thought we were running tests in Vercel Preview, I don't follow?

I think you should either rewrite it from scratch seriously or unpublish it. An article like that brings us nothing and on the contrary, serves us badly I think.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +- **Increasing test reliability**: Visual testing on a production-like environment.
Duplicate.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +**Note:** This method is optimal for repeatable tests that don't significantly alter the environment, as certain tests (e.g. those involving user deletion) may not be applicable.
I don't understand.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +- **Reducing CI cost:** Eliminating the need to set up a second environment to run the tests.
Avoid building your app twice.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +Argos now seamlessly integrates with Vercel Preview for visual testing, offering a streamlined approach to catch visual regressions in a production-like environment. In this step-by-step guide, I sho
Rephrase without "streamlined".

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +1. Set up a [Next.js](https://nextjs.org/) project with [Playwright](https://playwright.dev).
There is a dedicated link for that on Next.js doc.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +2. Integrated Playwright tests into CI/CD.
Useless

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +[Signed up into Argos](https://app.argos-ci.com/signup) and import my project. In response, Argos generated an `ARGOS_TOKEN` for my repository that I saved it for later usage.
Badly said.

Signup to Argos and import your project. Save the `ARGOS_TOKEN` for later.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +### 1. Project Importation to Argos
Import your project in Argos

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +### 2. Package Installation
Install Argos Playwright SDK

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +Before integrating Argos into Vercel Preview for visual testing, I have:
Remove

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +```
Add comments in the code.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +I utilized the [Screenshot pages script](https://argos-ci.com/docs/screenshot-pages-script) from Argos's documentation for capturing my application's homepage. This script is flexible for adding more
I started with the [screenshot pages script](). For now I only capture the homepage but I will be able to easily add pages in the future.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +const baseUrl = "http://localhost:3000";
Remove, if you do that it does not work because you don't take the `process.env.BASE_URL`.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +  // { name: "pricing", path: "/pricing" },
Remove

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +});
It would be more elegant to iterate and generate one test per page, we should try that and update docs if possible.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +### 5. Set up ARGOS_TOKEN and test integration
```suggestion
### 5. Set up `ARGOS_TOKEN` and test integration
```

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +First, I set up `ARGOS_TOKEN` as a repository secret on GitHub. Then, I'm ready to push my code to GitHub monitor the status checks to ensure everything is working as expected: Playwright, Vercel, an
Badly said.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +![Github tests with Argos](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/om5itnow41f3koolbwio.png)
At this point we should not have any test running.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +To run my tests on Vercel Preview, I updated my CI workflow file:
Why setup CI with a wrong file then modify it? Just setup Playwright and the good CI file, no need to setup a wrong CI file. This article is not "Migrate from local testing to Vercel Preview testing".

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +        # 👉 Add this variables
It's "these".

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +For a comprehensive explanation of each step, read [Argos documentation](https://argos-ci.com/docs/run-on-preview-deployment).
I don't want to have to read another article, just explain me what you are doing here.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +    // Hide vercel toolbar in tests
```suggestion
    // Hide Vercel Toolbar in tests
```

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +    // Hide vercel toolbar in tests
It's not "vercel", it's "Vercel", please be careful with trademarks.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +![Github pull-request check statuses](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/qhp02ieazr6f38o8q915.png)
```suggestion
![GitHub pull request check statuses](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/qhp02ieazr6f38o8q915.png)
```

Please be careful with trademarks!!!

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +- [Github Repository](https://github.com/jsfez/argos-vercel-preview)
```suggestion
- [GitHub Repository](https://github.com/jsfez/argos-vercel-preview)
```

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +- [Pull Request #2 - Execute Argos on Vercel Preview](https://github.com/jsfez/argos-vercel-preview/pull/2)
I don't care about the PR number, really.

2024-02-02 22:38 UTC, gregberge commented on articles/vercel-preview/index.mdx
> +Vercel Preview and Argos serve complementary roles in ensuring web development excellence. Vercel Preview focuses on verifying expected outcomes, while Argos excels at detecting visual regressions ac
It smells AI.

2024-02-25 09:52 UTC, jsfez commented
I should have stick to the first version and ship it. Now the momentum is lost. I suggest to delete this PR

2024-04-01 08:41 UTC, closed without merging